language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t ladis29/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true ladis29/react-test npm test -- --coverage

after_success:
  - docker build -t ladis29/multi-client ./client
  - docker build -t ladis29/multi-nginx ./nginx
  - docker build -t ladis29/multi-server ./server
  - docker build -t ladis29/multi-worker ./worker
  # Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login --username "$DOCKER_ID" --password-stdin
  # Take those images and push them to docker hub
  - docker push ladis29/multi-client
  - docker push ladis29/multi-nginx
  - docker push ladis29/multi-server
  - docker push ladis29/multi-worker

deploy:
  provider: elasticbeanstalk
  region: "us-east-1"
  app: "multi-docker"
  env: "MultiDocker-env"
  bucket_name: "elasticbeanstalk-us-east-1-631722500139"
  bucket_path: "docker-multi"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: $AWS_SECRET_KEY